# mpv keybindings

## Seek units are in seconds, but note that these are limited by keyframes
RIGHT seek  5                          # seek 5 seconds forward
LEFT  seek -5                          # seek 5 seconds backward
UP    seek  60                         # seek 1 minute forward
DOWN  seek -60                         # seek 1 minute backward
.     sub-seek 1                       # jump to next subtitle
,     sub-seek -1                      #         previous
Z  add secondary-sub-delay -0.1
X  add secondary-sub-delay +0.1

# Tekan Option+1 untuk Streaming (Matikan FFmpeg)
alt+1 apply-profile streaming-mode; show-text "Mode: Streaming (FFmpeg OFF)"

# Tekan Option+2 untuk Lokal (Nyalakan FFmpeg)
alt+2 apply-profile local-mode; show-text "Mode: Lokal (FFmpeg ON)"