# you can disable lines of this config by commenting them out by placing a '#' at the start of the line
hwdec=auto-safe

# set audio and subtitle language to Japanese.
ytdl-format="sub_1080p/sub_720p/sub_360p/bestvideo+bestaudio/best"
alang=jpn,ja,jp,Japanese
slang=jpn,ja,Japanese,ind,id,Indonesian,eng,en,english, enUS, en-US
secondary-sid=auto
# you can change target language by editing jpn,jp,ja to other language codes: e.g. for Korean: kor,kr,ko

# you can press 'v' to toggle subtitles (to watch raw)
# uncomment this to disable subtitles by default
# sid=no

autocreate-playlist=same
audio-display=no
fs=yes
sub-auto=fuzzy

osd-bar=no

# ========== STYLING ==========
sub-font                     ="Hiragino Kaku Gothic ProN W6"
sub-font-size                =45
sub-color                    ="#FFFFFF"
sub-border-size              =2
sub-shadow-offset            =1
sub-pos                      =95

secondary-sub-ass-override   =yes
secondary-sub-delay          =0
secondary-sub-pos            =10

# ========== INTERFACE & YTDL ==========
idle=yes
force-window=yes
tls-verify=no

# Identitas penipu agar server HiAnime/Megacloud gak rese
user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
http-header-fields="Referer: https://megacloud.blog/"

# ========== PROFILE STREAMING ==========
[streaming-mode]
# Paksa yt-dlp buat ikutan bypass sertifikat
ytdl-raw-options=ignore-config=,tls-verify=no,no-check-certificate=
script-opts-append=yomipv-audio_use_ffmpeg=no
script-opts-append=yomipv-picture_use_ffmpeg=no
script-opts-append=yomipv-picture_animated=no

[local-mode]
script-opts-append=yomipv-audio_use_ffmpeg=yes
script-opts-append=yomipv-picture_use_ffmpeg=yes
script-opts-append=yomipv-picture_animated=yes
script-opts-append=yomipv-picture_format=webp